config/routes.rb
Rails.application.routes.draw do
  get 'invoice' => 'invoices#show', as: 'invoice'
  get 'invoice/:order_id' => 'invoices#service', as: 'service_invoice'
  get 'invoice/deal/:order_id' => 'invoices#deal', as: 'deal_invoice'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'passport/index'

  mount Commontator::Engine => '/commontator'

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  mount Monologue::Engine, at: '/blog'
 
  constraints :subdomain => "admin" do
    scope :module => 'fpadmin' do
      resources :partners do
        post 'activate', on: :member
      end
      resources :customers
      resources :reservations
      resources :orders
      resources :sessions
      resources :coupons
      resources :centers
      resources :trainers
      resources :deals

      get '/' => 'sessions#new'
      get '/iv_generator/:id' => 'invoice#show', as: :iv_generator
      get '/service_iv_generator/:id' => 'invoice#service', as: :service_iv_generator
      get '/deal_iv_generator/:id' => 'invoice#deal', as: :deal_iv_generator

      get '/services/cc/:customer_id' => 'services#customer_confirmation', as: :customer_confirmation
    end
  end

  constraints :subdomain => "partners" do
    scope :module => 'partners', :as => 'partners' do
        resources :instructors
        resources :classes
        resources :centers do
          resources :services, :galleries
        end
        resources :orders, :only => [:index, :show]
        resource :reservations
        resource :settings

        post 'login' => 'sessions#create'
        delete 'logout' => 'sessions#destroy'
        match '/' => 'sessions#new', via: [:get]
    end
  end

    get 'settings/change_password' => 'partners/settings#change_password', :as => 'change_password_partners_settings', :subdomain => 'partners'

    resources :customers, only: [:edit, :create, :update]
    resources :partners, only: [:index, :new, :create]

  get 'mypackage' => 'mypackage#index'
  post 'mypackage/success'
  post 'mypackage/failure'

  get 'checkout' => 'checkout#step1', :as => 'checkout'
  post 'checkout' => 'checkout#create'
  get 'checkout/step2'
  get 'checkout/success'
  get 'details/:center' => 'details#index', as: 'details_page'

  get 'payments/index'
  post 'payments/success'
  post 'payments/failure'

  get 'bookings/:center_id/:id/index' => 'bookings#index', as: 'book_now'
  post 'bookings/create'
  get 'bookings/:center_id/:id/add_details' => 'bookings#add_details', as: 'add_details'

  post '/rate' => 'rater#create', :as => 'rate'

  namespace :admins do
    resources :customers, :partners, :approvals, :populars
    resource :sessions
    get 'partners/list/index' => 'partners#list'
    post 'partners/list/:id' => 'partners#setpassword'
  end

  get 'partners(/:id)/dashboard' => 'partners/dashboard#summary', :as => 'partners_dashboard'

  get 'customerdashboard/details'
  patch 'customerdashboard/details_update'

  resources :categories, :only => [] do
    resources :populars, :only => [:index, :create]
  end

  namespace :customers do
    resources :details, :bookings, :mypass, :classes
    resources :profiles, only: [:edit, :update]
    resources :referrals
  end
  resources :reserves

  resources :sessions, :only => [:new, :create, :destroy]
  get 'auth/facebook/callback' => 'sessions#facebook'

  resources :password_resets
  get 'customer/change_password' => 'password_resets#change_password'
  patch 'customer/update_password' => 'password_resets#update_password'

  get 'registrations/partner'
  post 'registrations/partner_signup', :as => 'partner_signup'

  get 'registrations/verify_email/:token' => 'registrations#verify_email', :as => 'registrations_verify_email'
  get 'registrations/customer'
  post 'registrations/customer_signup', :as => 'customer_signup'

  resources :coupons, :only => [:create]
  resources :centers, :only => [] do
    member do
      get :about
      get :map
      get :reviews
      get :instructors
      get :experience
      get :hours
      get :upcoming
    end
    resources :categories, :only => [] do
      resources :services, :only => [:index]
    end
  end

  get 'search' => 'filters#search'
  get 'classes/search' => 'filters#classes'
  post 'api/search' => 'filters#react_search'
  post 'api/search/classes' => 'filters#react_class_search'
  get 'api/center_types' => 'filters#center_types'
  get 'api/dates' => 'filters#dates'

  get 'homepage/index'
  get 'centers/list' => 'homepage#centers_list'

  resource 'trainers'
  resources 'book_service'
  post 'book_service/success'
  post 'book_service/failure'
  
  get '/request-trainer' => 'trainers#new'
  get '/services' => 'services#index'
  post '/api/services' => 'services#search'

  resources :deals
  resources :book_deal
  post 'book_deal/success'
  post 'book_deal/failure'

  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
      scope module: :v1 do
      end
  end

  get "cities/:city_id/areas" => "application#areas", :as => "areas", :format => :json

  root :to => 'homepage#index'

  if Rails.env.production?
    match '/404', to: 'errors#file_not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all
  end
end

app/controllers/customers/bookings_controller.rb
# Old Controller 

module Customers
class BookingsController < ApplicationController 
layout 'customerdashboard'
  def index
  	@bookings = Booking.where('customer_id=?', current_user.id).where('service_type=?', 1).includes(:service)
  end
end
end

app/controllers/customers/classes_controller.rb
# Customers >> My class

module Customers
class ClassesController < ApplicationController 
layout 'customerdashboard'
 
  # Customers >> My Class, History
  def index
  	@passport = passport
  	@total = passport.try(:remaining_tickets) || 0 
    @active = passport.try(:total_active_clasbkings) || 0
    @bookings = @passport.clasbkings.includes(:fpclass) unless @passport.nil?
  	@history = Clasbking.unscoped.where('customer_id=?', current_user.id).where('expired_at < ?', Time.now)
  end

  # Customers >> My Orders
  def show
  	@passport = passport
    # reject will remove orders that does not contain service order items 
    @orders = current_user.success_orders.includes(:service_order_item).reject{|o| o.service_order_item.blank? }
    @deal_orders = current_user.success_orders.includes(:deal_order_item).reject{|o| o.deal_order_item.blank? }
  end

  def color 
    false
  end
end
end

app/controllers/customers/details_controller.rb
# Old Controller

module Customers
class DetailsController < ApplicationController 
before_filter :authenticated?
layout 'customerdashboard'
before_filter { @details = current_user }

  def index
    # If we fetch from center method below then it'll not update the record
    @email = @details.customer.email
  end

  def update
    
  end
  
  def create
    if @details.update_attributes(permit_params)
      flash[:notice] = 'Updated'
      redirect_to customers_details_path
    else
      render :text => "Something went wrong"
    end
  end

  private
  	def permit_params
  		params.require(:user).permit("first_name","centertype_id","address1","address2","area_id","city_id","image","phone","emergency_phone", "emergency_name")
  	end
end
end

app/controllers/customers/mypass_controller.rb
# Old Controller

module Customers
class MypassController < ApplicationController 
layout 'customerdashboard'
  def index
  	mypasses = []
  	@mypasses = current_user.orders.includes(:order_items).each {|order| mypasses << order.order_items}.flatten
  end
end
end

app/controllers/customers/profiles_controller.rb
# Customers >> My Profile

module Customers
class ProfilesController < ApplicationController 
before_filter :authenticated?
layout 'customerdashboard'
before_filter { @c = current_user.user }

  def edit
    @user = current_user
  end

  def update
    if @c.update_attributes(permit_params)
      flash[:notice] = 'Details Updated'
      redirect_to edit_customers_profile_path('v1')
    else
      flash[:notice] = "Something went wrong"
      render 'edit'
    end
  end

  def color 
    false
  end
  
  private
  	def permit_params
      params.require(:user).permit(:phone, :dob, :location, :address1, :address2, :emergency_name, :emergency_phone, :image)
  	end
end
end

app/controllers/customers/referrals_controller.rb
## Customers >> Refer & Earn

module Customers
class ReferralsController < ApplicationController
layout 'customerdashboard'
  def index
  	
  end
end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
layout 'homepage'

  def index

  end

  def edit
    @user = User.find_by_remember_token(params[:id])
    @customer = @user.customer
  end

  def create
    @customer = Customer.find_by_email(params[:customer][:email]) || Customer.new(permit_params)
    @customer.set_referrer(cookies['h_ref']) unless cookies['h_ref'].blank?
    cookies['h_ref'] = nil
  	if !@customer.active && @customer.save
      # AdminMailer.customer_registration(@customer).delay.deliver
      RegistrationMailer.send_manual(@customer).deliver
      respond_to do |format|
          format.js
      end
      #redirect_to page_path('verify')
  	else
      render :js => "alert('Email-Id already exists with FitnessPapa')"
  	end
  end


  def update
    @user = User.find_by_remember_token(params[:token]) 
    @customer = @user.customer
    if @customer.update_attributes(update_params) && @customer.user.update!(:active => true, :location => @user.location)
      env['warden'].set_user(@customer.user)
      redirect_to search_path, :notice => "Registration completed."
    else
      render :text => "something went wrong"
    end
  end

  private
  	def permit_params
  		params.require(:customer).permit(:email, :user_attributes => [:location])
  	end

    def update_params
      params.require(:customer).permit(:user_attributes => [:full_name, :phone, :password])
    end
end

app/controllers/fpadmin/base_controller.rb
module Fpadmin
class BaseController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :warden, :current_user


  def current_user
   warden.user(:superadmin)
  end

  def warden
    request.env['warden']
  end

  def authenticate!
    # redirect_to partners_path unless warden.authenticated?(:partner)
    # authenticate_or_request_with_http_basic do |username, password|
    #     username == "foo" && password == "bar"
    # end
  end

  def authenticated?
    redirect_to new_session_path if current_user.blank?
  end
end
end

app/controllers/fpadmin/centers_controller.rb
## Admin Dashboard >> Centers

module Fpadmin
class CentersController < BaseController 
layout 'fpadmin'
before_filter :authenticated?

  def index
    @q = Center.ransack(params[:q])
    @q.build_condition if @q.conditions.empty?
    @q.build_sort if @q.sorts.empty?
    @centers = @q.result.page(params[:page])
  end

  def update
    @center = Center.find(params[:id])
    if @center && @center.update_attributes(permit_params)
      render js: "$('#center_#{params[:id]} .btn').val('updated')"
    else
      render js: "alert('Something went wrong');"
    end
  end

  private
    def permit_params
      params.require(:center).permit(:pricetag)
    end
end
end

app/controllers/fpadmin/coupons_controller.rb
# Admin Dashboard >> Coupons

module Fpadmin
class CouponsController < BaseController
layout 'fpadmin'
before_filter :authenticated?

  def index
   @coupons = Coupon.all
  end

  def new
    @coupon = Coupon.new
  end

  def create
    @coupon = Coupon.new(permit_params)
    if @coupon.save
      redirect_to action: :index, :notice => "Coupon Added"
    else
      render 'new'
    end
  end

  def destroy
  end

  private
    def permit_params
      params.require(:coupon).permit(:code, :expires_at, :percent, :amount)
    end
end
end

app/controllers/fpadmin/customers_controller.rb
# Admin Dashboard >> Customers

module Fpadmin
class CustomersController < BaseController 
layout 'fpadmin'
before_filter :authenticated?

  def index
    @customers = Customer.recent.includes(:user, :passport).page params[:page]
  end

  def show
    @customer = Customer.find(params[:id])
    @order = @customer.passport
    @reservations = @order.blank? ? nil : @order.clasbkings
  end

  def destroy
  	@customer = Customer.find(params[:id])
  	if @customer.destroy
  		redirect_to :action => 'index'
  	else
  		render :text => 'something went wrong'
  	end
  end
end
end

app/controllers/fpadmin/deals_controller.rb
## Admin Dashboard >> Deals

module Fpadmin
class DealsController < BaseController 
layout 'fpadmin'
before_filter :authenticated?

  def index
    @deals = Deal.all
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(permit_params)
    @deal.category = params[:deal][:category].last
    if @deal.save
      flash[:notice] = "Deal Created successfully"
      redirect_to action: :index
    else
      render :new
    end
  end

  private
    def permit_params
      params.require(:deal).permit(:brand, :bemail, :bmobile, :name, :address, :original_price, :selling_price, :about, :quantity, :city, :sublocation, :image, :subcategory => [], :timings => [])
    end
end
end

app/controllers/fpadmin/invoice_controller.rb
# Admin Dashboard >> Orders >> Invoice

module Fpadmin
class InvoiceController < BaseController 
layout 'fpadmin'
before_filter :authenticated?

  def show
   @passport = Passport.unscoped.find(params[:id]) 
   respond_to do |format|
     format.pdf {
       send_data @passport.receipt.render,
         filename: "#{@passport.created_at.strftime("%Y-%m-%d")}-fitnesspapa-receipt.pdf",
         type: "application/pdf",
         disposition: :inline
     }
   end
  end

  def service
    @order = Order.find_by_number(params[:id])
    @service = @order.service_order_item.service
    respond_to do |format|
       format.pdf {
         send_data @service.receipt(@order).render,
           filename: "#{@order.updated_at.strftime("%Y-%m-%d")}-fitnesspapa-receipt.pdf",
           type: "application/pdf",
           disposition: :inline
       }
     end
  end

  def deal
    @order = Order.find_by_number(params[:id])
    @deal = @order.deal_order_item.deal
    respond_to do |format|
       format.pdf {
         send_data @deal.receipt(@order).render,
           filename: "#{@order.updated_at.strftime("%Y-%m-%d")}-fitnesspapa-receipt.pdf",
           type: "application/pdf",
           disposition: :inline
       }
     end
  end
end
end

app/controllers/fpadmin/orders_controller.rb
## Admin Dashboard >> Orders 

module Fpadmin
class OrdersController < BaseController 
layout 'fpadmin'
before_filter :authenticated?

  def index
	@orders = Passport.unscoped.recent.includes(:customer).page params[:page] if params[:services].blank?
	@service_orders = OrderItem.services.includes(:order, :service) unless  params[:services].blank?
	@deal_orders = OrderItem.deals.includes(:order, :deal) unless  params[:deals].blank?
  end

  def show
  	
  end

  def destroy

  end
end
end

app/controllers/fpadmin/partners_controller.rb
## Admin Dashboard >> Partners

module Fpadmin
class PartnersController < BaseController 
layout 'fpadmin'
before_filter :authenticated?

  def index
    @partners = Partner.recent.includes(:user, :centers).page params[:page]
  end

  def show
    @partner = Partner.find(params[:id])
    @centers = @partner.centers
  end

  def destroy
  	@partner = Partner.find(params[:id])
  	if @partner.destroy
  		redirect_to :action => 'index'
  	else
  		render :text => 'something went wrong'
  	end
  end

  def activate
    @partner = Partner.find(params[:id])
    if @partner.user.update(:password => 'fpadjko7542', :active => 'true')
      redirect_to :action => 'index'
    else
      render :text => 'something went wrong'
    end

  end
end
end

app/controllers/fpadmin/reservations_controller.rb
## Myadmin >> Reservations

module Fpadmin
class ReservationsController < BaseController 
layout 'fpadmin'
before_filter :authenticated?

  def index
    @reservations = Clasbking.recent.includes(:customer, :fpclass, :center).page params[:page]
    @history = Clasbking.unscoped.where('expired_at < ?', Time.now).includes(:customer, :fpclass, :center).page params[:page]
  end

  def show

  end

  def destroy

  end
end
end

app/controllers/fpadmin/services_controller.rb
# Admin Dashboard >> Services

module Fpadmin
class ServicesController < BaseController 
layout 'fpadmin'
before_filter :authenticated?

  def customer_confirmation
    @customer = Customer.find(params[:customer_id])
    if @customer && RegistrationMailer.send_manual(@customer).delay.deliver
      render :js => "swal('Success', 'Confirmation Sent to #{@customer.full_name}', 'success');"
    else
      render :js => 'swal("Oops...", "Something went wrong!", "error");'
    end
  end

end
end

app/controllers/fpadmin/trainers_controller.rb
## Admin Dashboard >> Trainers

module Fpadmin
class TrainersController < BaseController 
layout 'fpadmin'
before_filter :authenticated?

  def index
   @trainers = Trainer.all
  end

end
end

app/views/fpadmin/customers/index.html.erb
<div class="main-header clearfix">
    <div class="page-title">
        <h3 class="no-margin">Customers</h3>
        <span></span>
    </div><!-- /page-title -->
    
    <ul class="page-stats">
    </ul><!-- /page-stats -->
</div>


<div class="padding-md">
    <div class="panel panel-default table-responsive">
        <div class="panel-heading">
            <span>Customers</span>
            <span class="pull-right">
                <%= paginate @customers %>
            </span>
        </div>
        <table class="table table-striped table-responsive" id="responsiveTable">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Location</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Passport</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @customers.each do |c| %>
                    <tr>
                        <td><%= link_to c.full_name, customer_path(:id => c.id) %></td>
                        <td><%= "#{c.location.split(',').first} #{c.location.split(',').second}" unless c.location.blank? %></td>
                        <td><%= c.phone %></td>
                        <td><a href="mailto:<%= c.email %>"><%= c.email %></a></td>
                        <td><span class="<%= c.passport.blank? ? "label label-danger" : "label label-success" %>"><%= c.passport.blank? ? "Inactive" : "Active" %></span></td>
                        <td><span class="<%= c.active ? "label label-success" : "label label-danger" %>"><%= c.active %></span>
                        <% unless c.active %>
                            <span><%= link_to "Resend", customer_confirmation_path(:customer_id => c.id), :class => 'label label-info', :remote => true, data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Sending..."} %></span>
                        <% end %>
                        </td>
                        
                        <td></td>
                    </tr>
                <%end%>
            </tbody>
        </table>
        <div class="panel-footer clearfix">
            <span class="pull-right">
                <%= paginate @customers %>
            </span>
        </div>
    </div>
</div>

app/views/fpadmin/customers/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel">
                <div class="panel-body">
                    <!-- <a href="#" class="pull-left avatar"> 
                        <img src="#" class="img-circle" alt="User Avatar"> 
                    </a> -->
                    <div class="pull-left m-left-sm">
                        <strong class="font-14 block"><%= @customer.full_name %></strong>
                        <small class="text-muted"><%= @customer.email %></small>
                        <small class="text-muted"><%= @customer.location %></small>
                        <div class="seperator"></div>
                    </div>
                    <div class="pull-right m-left-sm">
                        <strong class="font-14 block"> <%= @customer.emergency_name %></strong>
                        <small class="text-muted"> <%= @customer.emergency_phone %></small>
                        <div class="seperator"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6">
            <div class="panel panel-default table-responsive">
                <div class="panel-heading">
                    <span>Passports</span>
                    <span class="pull-right">
                    </span>
                </div>
                <table class="table table-striped table-responsive" id="responsiveTable">
                    <thead>
                        <tr>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Tickets Left</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% unless @order.blank? %>
                            <tr>
                                <td><%= local_time(@order.start_date, "%B %e, %Y") %></td>
                                <td><%= local_time(@order.end_date, "%B %e, %Y") unless @order.end_date.nil? %></td>
                                <td><%= @order.remaining_tickets  %></td>
                                <td></td>
                            </tr>
                        <% end %>
                </tbody>
                </table>
                <div class="panel-footer clearfix">
                    <span class="pull-right">
                        
                    </span>
                </div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="padding-md" style="padding-top:0px !important">
                <div class="panel panel-default table-responsive">
                    <div class="panel-heading">
                        <span>Reservations</span>
                    </div>
                    <table class="table table-striped table-responsive" id="responsiveTable">
                        <thead>
                            <tr>
                                <th>Class Name</th>
                                <th>Center Name</th>
                                <th>Date</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% unless @reservations.nil? %>
                                <% @reservations.each do |r| %>
                                    <tr>
                                        <td><%= r.fpclass.name %></td>
                                        <td><a href="mailto:<%= r.customer.try(:email) %>"><%= r.center.name %></a></td>
                                        <td><%= "#{r.expired_at} #{r.fpclass.start_time.strftime("%H:%M") unless r.fpclass.blank?}" %></td>
                                        <td></td>
                                    </tr>
                                <%end%>
                            <% end %>
                        </tbody>
                    </table>
                    <div class="panel-footer clearfix">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>