config/routes.rb
Rails.application.routes.draw do
  get 'invoice' => 'invoices#show', as: 'invoice'
  get 'invoice/:order_id' => 'invoices#service', as: 'service_invoice'
  get 'invoice/deal/:order_id' => 'invoices#deal', as: 'deal_invoice'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'passport/index'

  mount Commontator::Engine => '/commontator'

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  mount Monologue::Engine, at: '/blog'
 
  constraints :subdomain => "admin" do
    scope :module => 'fpadmin' do
      resources :partners do
        post 'activate', on: :member
      end
      resources :customers
      resources :reservations
      resources :orders
      resources :sessions
      resources :coupons
      resources :centers
      resources :trainers
      resources :deals

      get '/' => 'sessions#new'
      get '/iv_generator/:id' => 'invoice#show', as: :iv_generator
      get '/service_iv_generator/:id' => 'invoice#service', as: :service_iv_generator
      get '/deal_iv_generator/:id' => 'invoice#deal', as: :deal_iv_generator

      get '/services/cc/:customer_id' => 'services#customer_confirmation', as: :customer_confirmation
    end
  end

  constraints :subdomain => "partners" do
    scope :module => 'partners', :as => 'partners' do
        resources :instructors
        resources :classes
        resources :centers do
          resources :services, :galleries
        end
        resources :orders, :only => [:index, :show]
        resource :reservations
        resource :settings

        post 'login' => 'sessions#create'
        delete 'logout' => 'sessions#destroy'
        match '/' => 'sessions#new', via: [:get]
    end
  end

    get 'settings/change_password' => 'partners/settings#change_password', :as => 'change_password_partners_settings', :subdomain => 'partners'

    resources :customers, only: [:edit, :create, :update]
    resources :partners, only: [:index, :new, :create]

  get 'mypackage' => 'mypackage#index'
  post 'mypackage/success'
  post 'mypackage/failure'

  get 'checkout' => 'checkout#step1', :as => 'checkout'
  post 'checkout' => 'checkout#create'
  get 'checkout/step2'
  get 'checkout/success'
  get 'details/:center' => 'details#index', as: 'details_page'

  get 'payments/index'
  post 'payments/success'
  post 'payments/failure'

  get 'bookings/:center_id/:id/index' => 'bookings#index', as: 'book_now'
  post 'bookings/create'
  get 'bookings/:center_id/:id/add_details' => 'bookings#add_details', as: 'add_details'

  post '/rate' => 'rater#create', :as => 'rate'

  namespace :admins do
    resources :customers, :partners, :approvals, :populars
    resource :sessions
    get 'partners/list/index' => 'partners#list'
    post 'partners/list/:id' => 'partners#setpassword'
  end

  get 'partners(/:id)/dashboard' => 'partners/dashboard#summary', :as => 'partners_dashboard'

  get 'customerdashboard/details'
  patch 'customerdashboard/details_update'

  resources :categories, :only => [] do
    resources :populars, :only => [:index, :create]
  end

  namespace :customers do
    resources :details, :bookings, :mypass, :classes
    resources :profiles, only: [:edit, :update]
    resources :referrals
  end
  resources :reserves

  resources :sessions, :only => [:new, :create, :destroy]
  get 'auth/facebook/callback' => 'sessions#facebook'

  resources :password_resets
  get 'customer/change_password' => 'password_resets#change_password'
  patch 'customer/update_password' => 'password_resets#update_password'

  get 'registrations/partner'
  post 'registrations/partner_signup', :as => 'partner_signup'

  get 'registrations/verify_email/:token' => 'registrations#verify_email', :as => 'registrations_verify_email'
  get 'registrations/customer'
  post 'registrations/customer_signup', :as => 'customer_signup'

  resources :coupons, :only => [:create]
  resources :centers, :only => [] do
    member do
      get :about
      get :map
      get :reviews
      get :instructors
      get :experience
      get :hours
      get :upcoming
    end
    resources :categories, :only => [] do
      resources :services, :only => [:index]
    end
  end

  get 'search' => 'filters#search'
  get 'classes/search' => 'filters#classes'
  post 'api/search' => 'filters#react_search'
  post 'api/search/classes' => 'filters#react_class_search'
  get 'api/center_types' => 'filters#center_types'
  get 'api/dates' => 'filters#dates'

  get 'homepage/index'
  get 'centers/list' => 'homepage#centers_list'

  resource 'trainers'
  resources 'book_service'
  post 'book_service/success'
  post 'book_service/failure'
  
  get '/request-trainer' => 'trainers#new'
  get '/services' => 'services#index'
  post '/api/services' => 'services#search'

  resources :deals
  resources :book_deal
  post 'book_deal/success'
  post 'book_deal/failure'

  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
      scope module: :v1 do
      end
  end

  get "cities/:city_id/areas" => "application#areas", :as => "areas", :format => :json

  root :to => 'homepage#index'

  if Rails.env.production?
    match '/404', to: 'errors#file_not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all
  end
end

app/controllers/filters_controller.rb
## Search page

class FiltersController < ApplicationController
# before_filter { @c = Center.ransack(params[:q]) }
before_filter { redirect_to root_url unless current_user }
  def search
  end

  def react_search
    params[:q] = {:place_name_cont_any => params[:place_name_cont_any], :center_type_in => params[:center_type_in].blank? ? '' : JSON.parse(params[:center_type_in])} unless params[:place_name_cont_any].blank?
    @c = Center.ransack(params[:q])
    @centers = @c.result(distinct: true).includes(:centerinfo, :cphotos)
    render json: @centers
  end

  def react_class_search
    params_modifier

    @c = Fpclass.ransack(params[:q])
    start_time, end_time = params[:q][:time_filter].collect {|a| a.remove(":").to_i}
    @fpclasses = ClasFetcher.new(date, @c.result.any_classes(date).pluck(:id), {start_time: start_time, end_time: end_time}).fetch

    render json: [@fpclasses.sort! {|x, y| x['time'] <=> y['time'] }, dates_fetcher, passport ? passport.clasbkings : [], params[:q][:centers_place_name_cont_any]]
  end

  private
    def params_modifier
      params[:q] = {}
      params[:q].merge!({:centers_place_name_cont_any => params[:place_name_cont_any], :centers_center_type_in => JSON.parse(params[:center_type_in])}) unless params[:place_name_cont_any].blank?
      params[:q].merge!({:centers_slug_eq => params[:centers_slug_eq]}) unless params[:centers_slug_eq].blank?
      
      params[:q].reverse_merge!(
        :centers_place_name_cont_any => current_user.city_name,
        :time_filter => params[:time_filter].blank? ? ['01:00', '24:00'] : params[:time_filter].split(";"), 
      )
    end

    def dates_fetcher
      @dates = (Date.today..Date.today+6).to_a
    end

    def date
      params[:recursivedates_ondate_eq] ? params[:recursivedates_ondate_eq] : Date.today.strftime("%Y-%m-%d")
    end

    def fetch_timings
      
    end

    def color 
      false
    end
end

app/views/filters/_fpclass.html.erb
<tr id="fpclass_<%= fpclass.id %>">
	<td><h5><a href="<%= details_page_path(fpclass.try(:centers).try(:first).friendly_id) unless fpclass.try(:centers).try(:first).nil? %>"><%= fpclass.try(:centers).try(:first).try(:name).try(:capitalize) %></a></h5>
	</td>
	<td><h5>
		<%= link_to fpclass.name.capitalize, reserf_path(:id => fpclass.id), method: :get, remote: :true %></h5></td>
	<td><%= fpclass.start_time.strftime('%H : %M') unless fpclass.start_time.nil? %> | <span><%= fpclass.duration %> <span>Minutes</span></span></td>
	<td><%= fpclass.try(:centers).try(:first).try(:place_name).split(',')[0] unless fpclass.try(:centers).try(:first).try(:place_name).nil? %></td>
	<td class="text-center"><%= link_to 'Reserve', reserf_path(:id => fpclass.friendly_id, :date => params[:q][:recursivedates_ondate_eq]), :class => 'btn btn-primary reserve-btn', method: :get, remote: :true %><br><span class='fp-count'><%= pluralize(fpclass.remaining_seats, 'seats') %></span> <span>left</span></td>
</tr>

app/views/filters/_main_search.html.erb
<%= search_form_for @c, :url => classes_search_path, :remote => true do |f| %>
  <%= hidden_field_tag 'q[recursivedates_ondate_eq]', params[:q][:recursivedates_ondate_eq] %>
  <div class="row">
      <div class="col-md-3 col-xs-12 m-bottom20">
          <label for="location">LOCATION</label>
          <div>
            <input id="cities_two" type="text" name="q[centers_place_name_cont_any]" placeholder="<%= params[:q][:centers_place_name_cont_any] || 'Type Locality or Landmark' %>" class="ui-autocomplete-input form-control form-square" autocomplete="off" style="margin-bottom:20px">
          </div>
      </div>
      
      <div class="col-md-3 col-xs-12 m-bottom20">
        <label for="facilities">ACTIVITIES</label>
        <div>
          <%= f.collection_select :centers_center_type_in, Center::CENTERTYPES, :to_s, :to_s, {}, { :class => 'magicsuggest', :style => "margin-bottom:20px" } %>
        </div>
      </div>
      <div class="col-md-3 col-xs-12">
        <label for="">&nbsp;</label>
        <div>
          <%= f.submit '  Search  ', :class => 'btn btn-default', :style => 'margin-right:20px' %>
        </div>
      </div>
  </div>
<% end %>

app/views/filters/_pagination.html.erb
<div class="filter-result">
  <div class="pagination-filter">
  <div class="pagination-filter-main" style="width:100%;">
    <div class="page-detail">
      <p>Page 1 of 50</p>
    </div>
    <div class="prev">
      <a href="#">Prev</a>
    </div>
    <div class="num">
      <a href="#" class="active">1</a>
      <a href="#">2</a>
      <a href="#">3</a>
      <a href="#">4</a>
      <a href="#">5</a>
    </div>
    <div class="next">
      <a href="#">Next</a>
    </div>
  </div>
  </div>
</div>

app/views/filters/_search.html.erb
<div class="week1">
  <div id="sd-calendar" class="owl-carousel owl-theme">
     <% SimpleCalendar::Calendar.new(self, number_of_days: 14).date_range.each do |date| %>
      <div class="item">
	    	<% if !params['q'].blank?  %>
	  	    <% case date.strftime("%Y-%m-%d")
		        when params['q']['recursivedates_ondate_eq'] %><%= link_to date.strftime('%b %d'), classes_search_path(:q => {:recursivedates_ondate_eq => date, :centers_place_name_cont_any => params[:q][:centers_place_name_cont_any], :centers_center_type_in => params[:q][:centers_center_type_in]}), remote: true, class: 'label label-success' %>
		      <% else %><%= link_to date.strftime('%b %d'), classes_search_path(:q => {:recursivedates_ondate_eq => date, :centers_place_name_cont_any => params[:q][:centers_place_name_cont_any], :centers_center_type_in => params[:q][:centers_center_type_in]}), remote: true %>
		     <% end %>
	       <% end %>
       </div>
    	<%end%>  
  </div>
</div>

app/views/filters/classes.js.erb
$('#centers-section').hide();
$('#classes-section').fadeIn(1000);
$('#classes-content').html("<%= j render partial: 'fpclass', collection: @fpclasses %>");
$("#classes-search").html("<%= j render partial: 'search' %>");
$("#classes-main-search").html("<%= j render partial: 'main_search' %>");
$('#classes-search-container').fadeIn(1000);
$('#center-search-container').hide();


$('.magicsuggest').magicSuggest([]);
window.search_input2 = document.getElementById('cities_two');
window.city_name2 = new google.maps.places.Autocomplete(window.search_input2);


var owl = $("#sd-calendar");
owl.owlCarousel({
      items : 7, //10 items above 1000px browser width
      pagination: false,
      rewindNav: false,
      navigation: true,
      navigationText: [
       "<i class='icon-chevron-left icon-white'><</i>",
       "<i class='icon-chevron-right icon-white'>></i>"
      ],
  });

var owldata = $("#sd-calendar").data('owlCarousel');
owldata.jumpTo(<%= @difference.to_i %>)

app/views/filters/search.html.erb
<div class="row" style="background-color:#f1f5fc">
    <div id='search-container' class="container" style="min-height:450px">
    
    </div>
</div>

<div class="row">
  <div id="testing">
    
  </div>
</div>

<%= render 'homepage/passport' %>
<!-- Reserve modal is parent for model opens after reserve click -->
<div id="reserve-modal"></div>

<script>
  function togglefilter(){
    if($("#monthly").is(':checked')){
        if($('#center-search-container').hasClass("hidden-xs")){
          $('#center-search-container').removeClass("hidden-xs" , "slow");
        }else{
          $('#center-search-container').toggle('slow');
        }
    }else{
      if($("#classes-search-container").hasClass("hidden-xs")){
        $("#classes-search-container").removeClass("hidden-xs" , "slow");
      }else{
        $("#classes-search-container").toggle('slow');
      }
    }
  };
</script>

app/views/filters/search.js.erb
$("#fp-link").addClass('active');
$('#classes-section').hide();
$('#centers-section').fadeIn(1000);
<%unless @centers.blank? %>
	$('#centers-section').html("<%= j render @centers %>")
<%else%>
	$('#centers-section').html("<div class='row list-item' style='min-height:250px;padding:40px'><div class='container'><p class='text-info'>No centers found with your search criteria!</p></div></div>")
<%end%>
$('#classes-search-container').hide();
$('#center-search-container').fadeIn(1000);